# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb",
         "HelloSayer": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://josephsmann.github.io/nbdev_t2/"

git_url = "https://github.com/josephsmann/nbdev_t2/tree/master/"

def custom_doc_links(name): return None
