# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['say_hello']

# Cell
def say_hello(to):
    "say hello do to someone"
    print(f"Bonjiorno {to}")
    return f"Bonjiorno {to}"
