# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['say_hello', 'HelloSayer']

# Cell
# the export comment will put the function into the "core" module (as specificied in the ""# default_exp core" on the first line
# of notebook )
def say_hello(to):
    "say hello do to someone"
#     print(f"Bonjiorno {to}")
    return f"Bonjiorno {to}"


# Cell
class HelloSayer:
    # backticks in a doc string will link to the docs of the function
    "Say hello to `to` using `say_hello`"
    def __init__(self, to): self.to = to

    def say(self):
        "Do the saying"
        return say_hello(self.to)